---  #Update Remote Systems 
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  tasks: 
    - name: Update remore system
      yum:
        name: "*"
        state: latest
        
    - name: Reboot remote system
      command: reboot
   
